### ISSUE TITLE
Scan continues when hard limit switch is hit

### ISSUE THREAD

**Issue by skalbfleisch** [NSLS-II/ophyd#100]
ascan does not stop or give an error when scanned motor hits a _hard_ limit switch.

**Comment by tacaswell** [comment]
This should probably be implemented as the `set` commands raising exceptions when limits are hit which _should_ bubble up to bluesky and kill the scan.

**Comment by cowanml** [comment]
Seems like in most cases multiple things have already gone wrong if we
hit a hard limit?

I'd expect the scan to fail to start if an endpoint was past a soft limit,
suspend or stop if it somehow found itself passing a soft limit, and again
at a hard limit.  Is there any sort of detection/handling for stalled motors?

Ideally it should be made brutally obvious what the problem is and clear how
to recover and get back inside all limits.
